### ISSUE TITLE
Laser exceptions and white list limitations

### ISSUE THREAD

**Issue by BenjaminOrenstein** [rbecker5/BulletUpHell#12]
Consider the implementation of a cannon emitting lasers from it's center.  We want that laser to ignore the cannon itself, but we don't necessarily want it to ignore other cannons.  White/black lists enable us to ignore all cannons in a "Cannon" group but not individual ones.  Thankfully, RayCast2D gives us the tool we need and adding a function like this in Laser gives us access to it:
```

func add_exception(exception : CollisionObject2D):
	$RayCast2D.add_exception(exception)

```
I don't believe there is a clean way to do this currently implemented, but I may be wrong.

**Comment by Dark-Peace** [comment]
And so you're asking me to..?

**Comment by BenjaminOrenstein** [comment]
I have already implemented it for myself.  It seemed like an important missing feature and so I am passing it on to you.

**Comment by Dark-Peace** [comment]
Oh right, thank you.
