### ISSUE TITLE
Feature Request: The ability to add extra metadata to a bullet.

### ISSUE THREAD

**Issue by Ariber-Yadier** [rbecker5/BulletUpHell#6]
**What is your use-case ?**
In my game, I want to have multiple kinds of enemies where each enemy can shoot different bullets. I want these bullets to have different stats that the player node can react to when it collides with a bullet.

**Describe the feature you'd like**
I want to be able to add metadata to bullets, be it damage, the node who shot the bullet, or anything else.

**Describe alternatives you've considered**
I don't think there's any alternatives.

**Idea on how to make your feature**

**Additional context**

**Comment by Dark-Peace** [comment]
Have you considered using BulletProps.groups ?
It works like Godot groups, that's what I use for the damage in my game.

Also damage property comes in the next update.

**Comment by Dark-Peace** [comment]
Looks like I forgot to close this issue. This feature request has been implemented for a while now.
