### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by TomJamin** [rbecker5/BulletUpHell#8]
Good Morning. I hope you will see this because I really need your help. I downloaded the bulletuphell files for Godot 4.2 and once I get the files on to the Godot project this comes up

 res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/ExampleScenes/ExampleScene.gd:6 - Parse Error: Identifier "Spawning" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/ExampleScenes/ExampleScene.gd" with error "Parse error". (User)
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/ExampleScenes/PlayerTest.gd:5 - Parse Error: Identifier "Spawning" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/ExampleScenes/PlayerTest.gd" with error "Parse error". (User)
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHBulletNode.gd:25 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHBulletNode.gd:27 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHBulletNode.gd:66 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHBulletNode.gd:67 - Parse Error: Identifier "Spawning" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHBulletNode.gd" with error "Parse error". (User)
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHBulletProperties.gd:28 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHBulletProperties.gd:79 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHBulletProperties.gd:83 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHBulletProperties.gd:88 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHBulletProperties.gd:118 - Parse Error: Identifier "Spawning" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHBulletProperties.gd" with error "Parse error". (User)
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHInstanceLister.gd:9 - Parse Error: Identifier "Spawning" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHInstanceLister.gd" with error "Parse error". (User)
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHPattern.gd:85 - Parse Error: Identifier "Spawning" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHPattern.gd" with error "Parse error". (User)
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHSpawnPoint.gd:41 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHSpawnPoint.gd:72 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHSpawnPoint.gd:73 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHSpawnPoint.gd:73 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHSpawnPoint.gd:118 - Parse Error: Identifier "Spawning" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHSpawnPoint.gd" with error "Parse error". (User)
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHTriggerContainer.gd:21 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHTriggerContainer.gd:22 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHTriggerContainer.gd:23 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHTriggerContainer.gd:34 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHTriggerContainer.gd:35 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHTriggerContainer.gd:35 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHTriggerContainer.gd:38 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHTriggerContainer.gd:41 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHTriggerContainer.gd:74 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHTriggerContainer.gd:143 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHTriggerContainer.gd:162 - Parse Error: Identifier "Spawning" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/Nodes/BuHTriggerContainer.gd" with error "Parse error". (User)
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/SpawnPatterns/PatternCustomShape.gd:15 - Parse Error: Identifier "Spawning" not declared in the current scope.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/SpawnPatterns/PatternCustomShape.gd:15 - Parse Error: Cannot use simple "@export" annotation because the type of the initialized value can't be inferred.
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/SpawnPatterns/PatternCustomShape.gd" with error "Parse error". (User)
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/SpawnPatterns/PatternLine.gd:10 - Parse Error: Identifier "Spawning" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/SpawnPatterns/PatternLine.gd" with error "Parse error". (User)
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/BuH.gd:6 - Parse Error: Preload file "res://addons/BulletUpHell/Nodes/BuHPattern.gd" does not exist.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/BuH.gd:6 - Parse Error: Preload file "res://addons/BulletUpHell/Sprites/NodeIcons1.png" does not exist.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/BuH.gd:7 - Parse Error: Preload file "res://addons/BulletUpHell/Nodes/BuHBulletProperties.gd" does not exist.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/BuH.gd:7 - Parse Error: Preload file "res://addons/BulletUpHell/Sprites/NodeIcons2.png" does not exist.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/BuH.gd:8 - Parse Error: Preload file "res://addons/BulletUpHell/Nodes/BuHTriggerContainer.gd" does not exist.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/BuH.gd:8 - Parse Error: Preload file "res://addons/BulletUpHell/Sprites/NodeIcons3.png" does not exist.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/BuH.gd:9 - Parse Error: Preload file "res://addons/BulletUpHell/Nodes/BuHSpawnPoint.gd" does not exist.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/BuH.gd:9 - Parse Error: Preload file "res://addons/BulletUpHell/Sprites/NodeIcons14.png" does not exist.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/BuH.gd:10 - Parse Error: Preload file "res://addons/BulletUpHell/Nodes/BuHInstanceLister.gd" does not exist.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/BuH.gd:10 - Parse Error: Preload file "res://addons/BulletUpHell/Sprites/NodeIcons20.png" does not exist.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/BuH.gd:11 - Parse Error: Preload file "res://addons/BulletUpHell/Nodes/BuHBulletNode.gd" does not exist.
  res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/BuH.gd:11 - Parse Error: Preload file "res://addons/BulletUpHell/Sprites/NodeIcons19.png" does not exist.
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://BulletUpHell-Demo-V4.4/addons/BulletUpHell/BuH.gd" with error "Parse error". (User) 

(sorry for the load of text) I was wondering what could I do to fix all this up before may 20th

**Comment by Dark-Peace** [comment]
Classic installation issue. Remove the plugin, follow the installation steps in the documentation and it will work. Don't open an example scene before restarting Godot. From the errors it looks like it's was installed in the wrong folder.

I prefer getting questions on Discord. You're lucky that I just happened to check my GitHub notifications today.

**Comment by TomJamin** [comment]
Thank you so much
