### ISSUE TITLE
Laser => collided emits the wrong position for certain objects

### ISSUE THREAD

**Issue by BenjaminOrenstein** [rbecker5/BulletUpHell#9]
If I create a laser that points at a TileMap it always gives the same value for position. 

Presumably it should emit pos instead of pos-global_position.

**Comment by Dark-Peace** [comment]
Mmh yeah, I think you're correct, I should change that.

**Comment by BenjaminOrenstein** [comment]
Interestingly, even with this fix it sometimes seems to hit the wrong cell:

Imagine this map:

[1]<---      [2]

I use the following to find what cell was hit: 

<code>local_to_map(to_local(collision_point))</code>

Sometimes, but not always, I get the tile to the right of [1] instead of [1].

This seems like an issue with godot's Raycast2D and not with what you have created - though perhaps it's a configuration issue on my end?  I'm ultimately not really sure how to resolve this (I suppose I could calculate the point I'm checking to be slightly past the one returned but I hate that).

EDIT: Subtracting the normal from the position seems to fix this. Maybe I'm missing something but I hate that this is needed.

**Comment by Dark-Peace** [comment]
Mmmh
